"""European airport catalog used by the flight scanner.

Each entry is [IATA_CODE, "Airport Name, City, Country"]. Kept as a flat list
so callers can build country/region filters cheaply.
"""

from __future__ import annotations

from typing import List


EURO_AIRPORTS: List[List[str]] = [
    ["AAL", "Aalborg Airport, Aalborg, Denmark"],
    ["AAR", "Aarhus Airport, Aarhus, Denmark"],
    ["ABZ", "Aberdeen International Airport, Aberdeen, United Kingdom"],
    ["ACE", "Lanzarote Airport, Lanzarote, Spain"],
    ["ACH", "St. Gallen-Altenrhein Airport, Altenrhein, Switzerland"],
    ["ACI", "Alderney Airport, Alderney, Guernsey"],
    ["AGP", "Málaga-Costa del Sol Airport, Málaga, Spain"],
    ["AHO", "Alghero-Fertilia Airport, Alghero, Italy"],
    ["AJA", "Ajaccio Napoleon Bonaparte Airport, Ajaccio, France"],
    ["ALC", "Alicante-Elche Miguel Hernández Airport, Alicante, Spain"],
    ["AMS", "Amsterdam Airport Schiphol, Amsterdam, Netherlands"],
    ["ANR", "Antwerp International Airport, Antwerp, Belgium"],
    ["AOI", "Ancona Falconara Airport, Ancona, Italy"],
    ["ARN", "Stockholm Arlanda Airport, Stockholm, Sweden"],
    ["ATH", "Athens International Airport, Athens, Greece"],
    ["AVN", "Avignon-Provence Airport, Avignon, France"],
    ["BCM", "George Enescu International Airport, Bacău, Romania"],
    ["BCN", "Josep Tarradellas Barcelona-El Prat Airport, Barcelona, Spain"],
    ["BDU", "Bardufoss Airport, Bardufoss, Norway"],
    ["BEG", "Belgrade Nikola Tesla Airport, Belgrade, Serbia"],
    ["BER", "Berlin Brandenburg Airport, Berlin, Germany"],
    ["BES", "Brest Bretagne Airport, Brest, France"],
    ["BFS", "Belfast International Airport, Belfast, United Kingdom"],
    ["BGO", "Bergen Airport, Flesland, Bergen, Norway"],
    ["BGY", "Orio al Serio International Airport (Milan Bergamo), Bergamo, Italy"],
    ["BHD", "George Best Belfast City Airport, Belfast, United Kingdom"],
    ["BHX", "Birmingham Airport, Birmingham, United Kingdom"],
    ["BIA", "Bastia-Poretta Airport, Bastia, France"],
    ["BIO", "Bilbao Airport, Bilbao, Spain"],
    ["BIQ", "Biarritz Pays Basque Airport, Biarritz, France"],
    ["BJD", "Bakkafjörður Airport, Bakkafjörður, Iceland"],
    ["BLL", "Billund Airport, Billund, Denmark"],
    ["BLQ", "Bologna Guglielmo Marconi Airport, Bologna, Italy"],
    ["BMA", "Stockholm Bromma Airport, Stockholm, Sweden"],
    ["BNX", "Banja Luka International Airport, Banja Luka, Bosnia and Herzegovina"],
    ["BOD", "Bordeaux-Mérignac Airport, Bordeaux, France"],
    ["BOJ", "Burgas Airport, Burgas, Bulgaria"],
    ["BOO", "Bodø Airport, Bodø, Norway"],
    ["BRE", "Bremen Airport, Bremen, Germany"],
    ["BRI", "Bari Karol Wojtyła Airport, Bari, Italy"],
    ["BRN", "Bern Airport, Bern, Switzerland"],
    ["BRQ", "Brno-Tuřany Airport, Brno, Czech Republic"],
    ["BRS", "Bristol Airport, Bristol, United Kingdom"],
    ["BRU", "Brussels Airport, Brussels, Belgium"],
    ["BSL", "EuroAirport Basel Mulhouse Freiburg, Basel, Switzerland/France"],
    ["BTS", "M. R. Štefánik Airport, Bratislava, Slovakia"],
    ["BUD", "Budapest Ferenc Liszt International Airport, Budapest, Hungary"],
    ["BWE", "Braunschweig-Wolfsburg Airport, Braunschweig, Germany"],
    ["BZG", "Bydgoszcz Ignacy Jan Paderewski Airport, Bydgoszcz, Poland"],
    ["CAG", "Cagliari Elmas Airport, Cagliari, Italy"],
    ["CAL", "Campbeltown Airport, Campbeltown, United Kingdom"],
    ["CDG", "Charles de Gaulle Airport, Paris, France"],
    ["CFE", "Clermont-Ferrand Auvergne Airport, Clermont-Ferrand, France"],
    ["CFU", "Ioannis Kapodistrias International Airport, Corfu, Greece"],
    ["CGN", "Cologne Bonn Airport, Cologne, Germany"],
    ["CHQ", "Chania International Airport, Chania, Greece"],
    ["CIA", "Ciampino–G. B. Pastine International Airport, Rome, Italy"],
    ["CLJ", "Avram Iancu Cluj International Airport, Cluj-Napoca, Romania"],
    ["CLY", "Calvi-Sainte-Catherine Airport, Calvi, France"],
    ["CMF", "Chambéry-Savoie Airport, Chambéry, France"],
    ["CND", "Mihail Kogălniceanu International Airport, Constanța, Romania"],
    ["CPH", "Copenhagen Airport, Copenhagen, Denmark"],
    ["CRA", "Craiova International Airport, Craiova, Romania"],
    ["CRL", "Brussels South Charleroi Airport, Charleroi, Belgium"],
    ["CTA", "Catania-Fontanarossa Airport, Catania, Italy"],
    ["CWL", "Cardiff Airport, Cardiff, United Kingdom"],
    ["DBV", "Dubrovnik Airport, Dubrovnik, Croatia"],
    ["DEB", "Debrecen International Airport, Debrecen, Hungary"],
    ["DLM", "Dalaman Airport, Dalaman, Turkey"],
    ["DME", "Domodedovo International Airport, Moscow, Russia"],
    ["DNK", "Dnipro International Airport, Dnipro, Ukraine"],
    ["DOL", "Deauville-Normandie Airport, Deauville, France"],
    ["DRS", "Dresden Airport, Dresden, Germany"],
    ["DTM", "Dortmund Airport, Dortmund, Germany"],
    ["DUB", "Dublin Airport, Dublin, Ireland"],
    ["DUS", "Düsseldorf Airport, Düsseldorf, Germany"],
    ["EBA", "Elba Marina di Campo Airport, Elba, Italy"],
    ["EDI", "Edinburgh Airport, Edinburgh, United Kingdom"],
    ["EFL", "Kefalonia International Airport, Kefalonia, Greece"],
    ["EGC", "Bergerac Dordogne Périgord Airport, Bergerac, France"],
    ["EGS", "Egilsstaðir Airport, Egilsstaðir, Iceland"],
    ["EIN", "Eindhoven Airport, Eindhoven, Netherlands"],
    ["EMA", "East Midlands Airport, Derby/Leicester, United Kingdom"],
    ["ERF", "Erfurt-Weimar Airport, Erfurt, Germany"],
    ["ESB", "Esenboğa International Airport, Ankara, Turkey"],
    ["EVE", "Harstad/Narvik Airport, Evenes, Norway"],
    ["EXT", "Exeter Airport, Exeter, United Kingdom"],
    ["FAE", "Vágar Airport, Vágar, Faroe Islands"],
    ["FAO", "Faro Airport, Faro, Portugal"],
    ["FCO", "Leonardo da Vinci-Fiumicino Airport, Rome, Italy"],
    ["FDE", "Førde Airport, Førde, Norway"],
    ["FDH", "Friedrichshafen Airport, Friedrichshafen, Germany"],
    ["FKB", "Karlsruhe/Baden-Baden Airport, Baden-Baden, Germany"],
    ["FLR", "Florence Airport, Florence, Italy"],
    ["FMM", "Memmingen Airport, Memmingen, Germany"],
    ["FMO", "Münster Osnabrück International Airport, Münster, Germany"],
    ["FNC", "Madeira Airport, Funchal, Portugal"],
    ["FNI", "Nîmes-Alès-Camargue-Cévennes Airport, Nîmes, France"],
    ["FRA", "Frankfurt Airport, Frankfurt, Germany"],
    ["FRO", "Florø Airport, Florø, Norway"],
    ["FSC", "Figari-Sud Corse Airport, Figari, France"],
    ["FUE", "Fuerteventura Airport, Fuerteventura, Spain"],
    ["GDN", "Gdańsk Lech Wałęsa Airport, Gdańsk, Poland"],
    ["GCI", "Guernsey Airport, Guernsey, Guernsey"],
    ["GIB", "Gibraltar International Airport, Gibraltar, Gibraltar"],
    ["GLA", "Glasgow Airport, Glasgow, United Kingdom"],
    ["GNB", "Grenoble Alpes–Isère Airport, Grenoble, France"],
    ["GOA", "Genoa Cristoforo Colombo Airport, Genoa, Italy"],
    ["GOT", "Göteborg Landvetter Airport, Gothenburg, Sweden"],
    ["GPA", "Araxos Airport, Patras, Greece"],
    ["GRQ", "Groningen Airport Eelde, Groningen, Netherlands"],
    ["GRO", "Girona-Costa Brava Airport, Girona, Spain"],
    ["GRX", "Federico García Lorca Granada-Jaén Airport, Granada, Spain"],
    ["GRZ", "Graz Airport, Graz, Austria"],
    ["GVA", "Geneva Airport, Geneva, Switzerland"],
    ["HAJ", "Hannover Airport, Hanover, Germany"],
    ["HAM", "Hamburg Airport, Hamburg, Germany"],
    ["HAU", "Haugesund Airport, Haugesund, Norway"],
    ["HEL", "Helsinki-Vantaa Airport, Helsinki, Finland"],
    ["HER", "Heraklion International Airport, Heraklion, Greece"],
    ["HHN", "Frankfurt-Hahn Airport, Hahn, Germany"],
    ["HOV", "Ørsta-Volda Airport, Hovden, Norway"],
    ["HRK", "Kharkiv International Airport, Kharkiv, Ukraine"],
    ["HUM", "Humberside Airport, Hull, United Kingdom"],
    ["IAS", "Iași International Airport, Iași, Romania"],
    ["IBZ", "Ibiza Airport, Ibiza, Spain"],
    ["IEV", "Igor Sikorsky Kyiv International Airport (Zhuliany), Kyiv, Ukraine"],
    ["INI", "Niš Constantine the Great Airport, Niš, Serbia"],
    ["INN", "Innsbruck Airport, Innsbruck, Austria"],
    ["INV", "Inverness Airport, Inverness, United Kingdom"],
    ["IOM", "Isle of Man Airport, Castletown, Isle of Man"],
    ["IST", "Istanbul Airport, Istanbul, Turkey"],
    ["IVL", "Ivalo Airport, Ivalo, Finland"],
    ["JER", "Jersey Airport, Jersey, Jersey"],
    ["JMK", "Mykonos Airport, Mykonos, Greece"],
    ["JSI", "Skiathos International Airport, Skiathos, Greece"],
    ["JTR", "Santorini (Thira) International Airport, Santorini, Greece"],
    ["JYV", "Jyväskylä Airport, Jyväskylä, Finland"],
    ["KBP", "Boryspil International Airport, Kyiv, Ukraine"],
    ["KDL", "Kärdla Airport, Kärdla, Estonia"],
    ["KEF", "Keflavík International Airport, Reykjavik, Iceland"],
    ["KGS", "Kos International Airport, Kos, Greece"],
    ["KIR", "Kerry Airport, Tralee, Ireland"],
    ["KIV", "Chișinău International Airport, Chișinău, Moldova"],
    ["KKN", "Kirkenes Airport, Høybuktmoen, Kirkenes, Norway"],
    ["KLV", "Karlovy Vary Airport, Karlovy Vary, Czech Republic"],
    ["KLU", "Klagenfurt Airport, Klagenfurt, Austria"],
    ["KOI", "Kirkwall Airport, Kirkwall, United Kingdom"],
    ["KRK", "John Paul II International Airport Kraków-Balice, Kraków, Poland"],
    ["KRN", "Kiruna Airport, Kiruna, Sweden"],
    ["KRP", "Karup Airport, Karup, Denmark"],
    ["KRS", "Kristiansand Airport, Kjevik, Kristiansand, Norway"],
    ["KSU", "Kristiansund Airport, Kvernberget, Kristiansund, Norway"],
    ["KTW", "Katowice Airport, Katowice, Poland"],
    ["KUO", "Kuopio Airport, Kuopio, Finland"],
    ["KUN", "Kaunas Airport, Kaunas, Lithuania"],
    ["LBA", "Leeds Bradford Airport, Leeds, United Kingdom"],
    ["LBI", "Albi-Le Sequestre Airport, Albi, France"],
    ["LCA", "Larnaca International Airport, Larnaca, Cyprus"],
    ["LCJ", "Łódź Władysław Reymont Airport, Łódź, Poland"],
    ["LCY", "London City Airport, London, United Kingdom"],
    ["LDY", "City of Derry Airport, Derry, United Kingdom"],
    ["LED", "Pulkovo Airport, St. Petersburg, Russia"],
    ["LEI", "Almería Airport, Almería, Spain"],
    ["LEJ", "Leipzig/Halle Airport, Leipzig, Germany"],
    ["LGW", "Gatwick Airport, London, United Kingdom"],
    ["LGG", "Liège Airport, Liège, Belgium"],
    ["LIG", "Limoges - Bellegarde Airport, Limoges, France"],
    ["LHR", "Heathrow Airport, London, United Kingdom"],
    ["LIL", "Lille Airport, Lille, France"],
    ["LIN", "Linate Airport, Milan, Italy"],
    ["LIS", "Humberto Delgado Airport, Lisbon, Portugal"],
    ["LJU", "Ljubljana Jože Pučnik Airport, Ljubljana, Slovenia"],
    ["LLA", "Luleå Airport, Luleå, Sweden"],
    ["LNZ", "Linz Airport, Linz, Austria"],
    ["LPA", "Gran Canaria Airport, Las Palmas, Spain"],
    ["LPL", "Liverpool John Lennon Airport, Liverpool, United Kingdom"],
    ["LPP", "Lappeenranta Airport, Lappeenranta, Finland"],
    ["LPX", "Liepāja International Airport, Liepāja, Latvia"],
    ["LTN", "Luton Airport, London, United Kingdom"],
    ["LUG", "Lugano Airport, Lugano, Switzerland"],
    ["LUX", "Luxembourg Airport, Luxembourg City, Luxembourg"],
    ["LUZ", "Lublin Airport, Lublin, Poland"],
    ["LWO", "Lviv Danylo Halytskyi International Airport, Lviv, Ukraine"],
    ["LYS", "Lyon-Saint Exupéry Airport, Lyon, France"],
    ["MAD", "Adolfo Suárez Madrid-Barajas Airport, Madrid, Spain"],
    ["MAH", "Menorca Airport, Mahón, Spain"],
    ["MAN", "Manchester Airport, Manchester, United Kingdom"],
    ["MHG", "Mannheim City Airport, Mannheim, Germany"],
    ["MHQ", "Mariehamn Airport, Mariehamn, Åland Islands"],
    ["MLA", "Malta International Airport, Luqa, Malta"],
    ["MLH", "EuroAirport Basel Mulhouse Freiburg, Mulhouse, France"],
    ["MMX", "Malmö Airport, Malmö, Sweden"],
    ["MOL", "Molde Airport, Årø, Molde, Norway"],
    ["MPL", "Montpellier-Méditerranée Airport, Montpellier, France"],
    ["MRS", "Marseille Provence Airport, Marseille, France"],
    ["MSQ", "Minsk National Airport, Minsk, Belarus"],
    ["MST", "Maastricht Aachen Airport, Maastricht, Netherlands"],
    ["MUC", "Munich Airport, Munich, Germany"],
    ["MXP", "Malpensa Airport, Milan, Italy"],
    ["NAP", "Naples International Airport, Naples, Italy"],
    ["NCE", "Nice Côte d'Azur Airport, Nice, France"],
    ["NCL", "Newcastle International Airport, Newcastle upon Tyne, United Kingdom"],
    ["NOC", "Ireland West Airport Knock, Knock, Ireland"],
    ["NRN", "Weeze Airport, Weeze, Germany"],
    ["NTE", "Nantes Atlantique Airport, Nantes, France"],
    ["NUE", "Nuremberg Airport, Nuremberg, Germany"],
    ["NWI", "Norwich Airport, Norwich, United Kingdom"],
    ["ODS", "Odesa International Airport, Odesa, Ukraine"],
    ["OLB", "Olbia Costa Smeralda Airport, Olbia, Italy"],
    ["OMO", "Mostar International Airport, Mostar, Bosnia and Herzegovina"],
    ["OPO", "Francisco Sá Carneiro Airport, Porto, Portugal"],
    ["ORK", "Cork Airport, Cork, Ireland"],
    ["ORY", "Orly Airport, Paris, France"],
    ["OSD", "Åre Östersund Airport, Östersund, Sweden"],
    ["OSI", "Osijek Airport, Osijek, Croatia"],
    ["OSL", "Oslo Airport, Gardermoen, Oslo, Norway"],
    ["OSR", "Leoš Janáček Airport Ostrava, Ostrava, Czech Republic"],
    ["OST", "Ostend-Bruges International Airport, Ostend, Belgium"],
    ["OTP", "Henri Coandă International Airport, Bucharest, Romania"],
    ["OUL", "Oulu Airport, Oulu, Finland"],
    ["OVD", "Asturias Airport, Oviedo, Spain"],
    ["PAD", "Paderborn Lippstadt Airport, Paderborn, Germany"],
    ["PDL", "João Paulo II Airport, Ponta Delgada, Portugal"],
    ["PDV", "Plovdiv Airport, Plovdiv, Bulgaria"],
    ["PED", "Pardubice Airport, Pardubice, Czech Republic"],
    ["PEG", "Perugia San Francesco d'Assisi - Umbria International Airport, Perugia, Italy"],
    ["PFO", "Paphos International Airport, Paphos, Cyprus"],
    ["PIK", "Glasgow Prestwick Airport, Glasgow, United Kingdom"],
    ["PLQ", "Palanga International Airport, Palanga, Lithuania"],
    ["PMI", "Palma de Mallorca Airport, Palma de Mallorca, Spain"],
    ["PMO", "Falcone Borsellino Airport, Palermo, Italy"],
    ["PNA", "Pamplona Airport, Pamplona, Spain"],
    ["POZ", "Poznań-Ławica Henryk Wieniawski Airport, Poznań, Poland"],
    ["PRG", "Václav Havel Airport Prague, Prague, Czech Republic"],
    ["PRN", "Pristina International Airport, Pristina, Kosovo"],
    ["PSA", "Pisa International Airport, Pisa, Italy"],
    ["PUY", "Pula Airport, Pula, Croatia"],
    ["RHO", "Rhodes International Airport, Rhodes, Greece"],
    ["RIX", "Riga International Airport, Riga, Latvia"],
    ["RJK", "Rijeka Airport, Rijeka, Croatia"],
    ["RKV", "Reykjavík Airport, Reykjavík, Iceland"],
    ["RMU", "Región de Murcia International Airport, Murcia, Spain"],
    ["RNB", "Ronneby Airport, Ronneby, Sweden"],
    ["RNN", "Bornholm Airport, Rønne, Denmark"],
    ["RNS", "Rennes-Saint-Jacques Airport, Rennes, France"],
    ["ROV", "Platov International Airport, Rostov-on-Don, Russia"],
    ["RTM", "Rotterdam The Hague Airport, Rotterdam, Netherlands"],
    ["RVN", "Rovaniemi Airport, Rovaniemi, Finland"],
    ["RZE", "Rzeszów-Jasionka Airport, Rzeszów, Poland"],
    ["SAW", "Sabiha Gökçen International Airport, Istanbul, Turkey"],
    ["SBZ", "Sibiu International Airport, Sibiu, Romania"],
    ["SCQ", "Santiago-Rosalía de Castro Airport, Santiago de Compostela, Spain"],
    ["SCV", "Suceava International Airport, Suceava, Romania"],
    ["SDR", "Seve Ballesteros-Santander Airport, Santander, Spain"],
    ["SEN", "London Southend Airport, Southend-on-Sea, United Kingdom"],
    ["SJJ", "Sarajevo International Airport, Sarajevo, Bosnia and Herzegovina"],
    ["SKG", "Thessaloniki Airport, Thessaloniki, Greece"],
    ["SKP", "Skopje International Airport, Skopje, North Macedonia"],
    ["SNN", "Shannon Airport, Shannon, Ireland"],
    ["SOF", "Sofia Airport, Sofia, Bulgaria"],
    ["SOU", "Southampton Airport, Southampton, United Kingdom"],
    ["SPC", "La Palma Airport, La Palma, Spain"],
    ["SPU", "Split Airport, Split, Croatia"],
    ["STN", "Stansted Airport, London, United Kingdom"],
    ["STR", "Stuttgart Airport, Stuttgart, Germany"],
    ["SVG", "Stavanger Airport, Sola, Stavanger, Norway"],
    ["SVO", "Sheremetyevo International Airport, Moscow, Russia"],
    ["SVQ", "Seville Airport, Seville, Spain"],
    ["SVX", "Koltsovo International Airport, Yekaterinburg, Russia"],
    ["SXB", "Strasbourg Airport, Strasbourg, France"],
    ["SYY", "Stornoway Airport, Stornoway, United Kingdom"],
    ["SZG", "Salzburg Airport, Salzburg, Austria"],
    ["SZZ", "Solidarity Szczecin-Goleniów Airport, Szczecin, Poland"],
    ["TAT", "Poprad-Tatry Airport, Poprad, Slovakia"],
    ["TAY", "Tartu Airport, Tartu, Estonia"],
    ["TFN", "Tenerife North-Ciudad de La Laguna Airport, Tenerife, Spain"],
    ["TFS", "Tenerife South Airport, Tenerife, Spain"],
    ["TGD", "Podgorica Airport, Podgorica, Montenegro"],
    ["TIA", "Tirana International Airport Nënë Tereza, Tirana, Albania"],
    ["TIV", "Tivat Airport, Tivat, Montenegro"],
    ["TKU", "Turku Airport, Turku, Finland"],
    ["TLS", "Toulouse-Blagnac Airport, Toulouse, France"],
    ["TLN", "Toulon-Hyères Airport, Toulon, France"],
    ["TLL", "Tallinn Airport, Tallinn, Estonia"],
    ["TMP", "Tampere-Pirkkala Airport, Tampere, Finland"],
    ["TOS", "Tromsø Airport, Langnes, Tromsø, Norway"],
    ["TPS", "Trapani-Birgi Airport, Trapani, Italy"],
    ["TRD", "Trondheim Airport, Værnes, Trondheim, Norway"],
    ["TRF", "Sandefjord Airport, Torp, Sandefjord, Norway"],
    ["TRN", "Turin Airport, Turin, Italy"],
    ["TRS", "Trieste – Friuli Venezia Giulia Airport, Trieste, Italy"],
    ["TSR", "Timișoara Traian Vuia International Airport, Timișoara, Romania"],
    ["TUF", "Tours Val de Loire Airport, Tours, France"],
    ["TZX", "Trabzon Airport, Trabzon, Turkey"],
    ["UME", "Umeå Airport, Umeå, Sweden"],
    ["VAA", "Vaasa Airport, Vaasa, Finland"],
    ["VAR", "Varna Airport, Varna, Bulgaria"],
    ["VBY", "Visby Airport, Visby, Sweden"],
    ["VCE", "Venice Marco Polo Airport, Venice, Italy"],
    ["VIE", "Vienna International Airport, Vienna, Austria"],
    ["VKO", "Vnukovo International Airport, Moscow, Russia"],
    ["VLC", "Valencia Airport, Valencia, Spain"],
    ["VLL", "Valladolid Airport, Valladolid, Spain"],
    ["VNO", "Vilnius Airport, Vilnius, Lithuania"],
    ["VRN", "Verona Villafranca Airport, Verona, Italy"],
    ["VST", "Stockholm Västerås Airport, Västerås, Sweden"],
    ["VXO", "Växjö/Kronoberg Airport, Växjö, Sweden"],
    ["WAW", "Warsaw Chopin Airport, Warsaw, Poland"],
    ["WMI", "Warsaw Modlin Airport, Warsaw, Poland"],
    ["WRO", "Copernicus Airport Wrocław, Wrocław, Poland"],
    ["XRY", "Jerez Airport, Jerez de la Frontera, Spain"],
    ["ZAD", "Zadar Airport, Zadar, Croatia"],
    ["ZAG", "Zagreb Franjo Tuđman Airport, Zagreb, Croatia"],
    ["ZAZ", "Zaragoza Airport, Zaragoza, Spain"],
    ["ZRH", "Zurich Airport, Zurich, Switzerland"],
    ["ZTH", "Zakynthos International Airport, Zakynthos, Greece"],
]


def _extract_country(label: str) -> str:
    """Country is the last comma-separated segment of the label."""
    return label.rsplit(",", 1)[-1].strip()


def filter_by_country(countries: List[str]) -> List[List[str]]:
    """Return airports whose country (case-insensitive) is in `countries`."""
    wanted = {c.strip().lower() for c in countries}
    return [
        entry
        for entry in EURO_AIRPORTS
        if _extract_country(entry[1]).lower() in wanted
    ]


def all_countries() -> List[str]:
    """Sorted unique list of countries represented in EURO_AIRPORTS."""
    return sorted({_extract_country(entry[1]) for entry in EURO_AIRPORTS})
